package io.github.aglibs.lathe.maven;

import io.github.aglibs.lathe.core.FileUtil;
import io.github.aglibs.lathe.core.LatheLayout;
import io.github.aglibs.lathe.install.ServerInstaller;
import io.github.aglibs.lathe.install.SyncException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.maven.plugin.logging.Log;

// Writes .lathe/lathe-sync.sh [--tests] [module ...], the one command clients, the server, and the
// MCP server run to refresh .lathe/, so none of them compose a Maven command line. The script picks
// the tool when it runs (mvnd, else ./mvnw, else mvn), builds on the server launcher's JDK, and
// prints the exact command first so the user sees what runs.
final class SyncScriptWriter {

  private final Log log;

  SyncScriptWriter(final Log log) {
    this.log = log;
  }

  void write(final Path workspaceRoot) {
    final var latheDir = workspaceRoot.resolve(LatheLayout.LATHE_DIR);
    final var script = latheDir.resolve(LatheLayout.SYNC_SCRIPT);
    final String content = render();
    try {
      if (Files.isExecutable(script)
          && content.equals(Files.readString(script, StandardCharsets.UTF_8))) {
        return;
      }

      Files.createDirectories(latheDir);
      FileUtil.writeAtomically(latheDir, script, content, true);
      log.info("[sync] wrote %s".formatted(script));
    } catch (final IOException e) {
      throw new SyncException("lathe:sync failed to write %s".formatted(script), e);
    }
  }

  // A scoped sync needs both directions: -am builds the modules' upstream so they resolve against
  // fresh classes, and -amd rebuilds the downstream whose classpath a POM change alters. The build
  // cache stays off, since a cache hit skips javac and the test fork, where Lathe captures.
  static String render() {
    return """
        #!/bin/sh
        # Generated by lathe:sync -- do not edit. Usage: %s/%s [--tests] [module ...]
        cd "$(dirname "$0")/.." || exit 1
        %sif [ "$java_bin" != java ]; then
          export JAVA_HOME="$jhome"
        fi
        goal=%s
        if [ "$1" = "--tests" ]; then
          goal=test
          shift
        fi
        if command -v mvnd >/dev/null 2>&1; then
          mvn=mvnd
        elif [ -x ./mvnw ]; then
          mvn=./mvnw
        else
          mvn=mvn
        fi
        scope=
        if [ $# -gt 0 ]; then
          scope="-pl $(echo "$@" | tr ' ' ',') -am -amd"
        fi
        set -- "$mvn" --no-transfer-progress -Dmaven.build.cache.enabled=false $scope "$goal"
        echo "lathe-sync: $*" >&2
        exec "$@"
        """
        .formatted(
            LatheLayout.LATHE_DIR,
            LatheLayout.SYNC_SCRIPT,
            ServerInstaller.javaResolvePrologue(),
            LatheLayout.SYNC_PHASE);
  }
}
