invoker.goals=io.github.ag-libs:lathe-maven-plugin:${project.version}:init test-compile io.github.ag-libs:lathe-maven-plugin:${project.version}:sync
invoker.buildResult=success
invoker.preBuildHookScript=setup
